---
language: python
python: "3.6"

# Run jobs in containers.
sudo: false

# Create a build matrix for the different test jobs.
env:
  matrix:
    # Run python style checks.
    - TOX_ENV=pep8
    # Run python2.7 unit tests.
    - TOX_ENV=py27
    # Run python3.6 unit tests.
    - TOX_ENV=py36
    # Run coverage tests
    - TOX_ENV=cover

install:
  - pip install tox

script:
  # Run the tox environment.
  - tox -e ${TOX_ENV}
